### ISSUE TITLE
deprecate run argument to actions

### ISSUE THREAD

**Issue by maxheld83** [r-lib/ghactions#338]
it appears that the `runs` arguments to actions (which used to just be appended to `docker run` as `COMMAND` and `ARGS`), has been deprecated.

Now you can only overwrite entrypoint and args separately.

Like so:

```
- name: Download Cache
        uses: actions/gcloud/cli@d124d4b82701480dc29e68bb73a87cfb2ce0b469
        with:
          entrypoint: gsutil
          args: -m cp -r gs://ghactions-cache/lib.tar.gz /github/home/
```

Whereas before, we could:

```
action "Download Cache" {
  uses = "actions/gcloud/cli@d124d4b82701480dc29e68bb73a87cfb2ce0b469"
  runs = "gsutil -m cp -r gs://ghactions-cache/lib.tar.gz /github/home/"
}
```

Not a huge limitation, but something to be aware of.
Just slightly less convenient, I guess.
